[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200

# RPC endpoints for multi-chain deployment
[rpc_endpoints]
avalanche-testnet = "${AVALANCHE_TESTNET_RPC}"
base-testnet = "${BASE_TESTNET_RPC}"

# Etherscan API keys for contract verification (disabled for now)
# [etherscan]
# avalanche-testnet = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
# base-testnet = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
